name: Demo Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  First_Job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      